- name: multiplay-play1
  hosts: local
  connection: local
  tasks:
  - name: Play for Play 1 and Task1
    ansible.builtin.debug:
      msg: "Hello from Play 1 to task 1"
  - name: play form play 1 and Task2
    ansible.builtin.debug:
      msg: "Hello from play 1 to task2"
- name: Multiplay-play2
  hosts: local
  connection: local
  tasks:
  - name: play from Play 2 to task 1
    ansible.builtin.debug:
      msg: "Hello from play 2 to task 1"
  - name: play from play 2 to task 2
    ansible.builtin.debug:
      msg: "Hello from play 2 to task 2"